### ISSUE TITLE
Limit selling mining materials to either Foreman or General Shop

### ISSUE THREAD

**Issue by capSAR273** [capSAR273/TheWastes#12]
I think the player should only be able to sell mining materials to one or the other, seems a little redundant to be able to sell to both, but that might just be my preference!

**Comment by Huw2k8** [comment]
This wont be changed, the foreman is a shitty alternative, if you notice the foreman pays less than the shop. but not all towns have shops, so you might arrive in the first town you've seen in 100 encounters and you've collected a heap of ore but there's no one you can sell it to.

The foreman was added so that no matter what if you can mine ore somewhere you can sell it.
