### ISSUE TITLE
Typo in city description

### ISSUE THREAD

**Issue by KaiserPodge** [capSAR273/TheWastes#21]
In the initial description it seems the description is showing brackets around one of the variables.  Once in the city itself it's normal.

> ## you find a Wasteland City, a man calls out and the gate rises
> 
> Inside you discover the town's name is Damnedburn Town the town is [bustling wit
> h activity] there are numerous guards posted and patrolling and there are many s
> hops and traders dotted around inside
> Press any key to continue . . .

**Comment by Huw2k8** [comment]
I shall be fixing this in the next update when I expand towns, it;s not shown but at the moment every town/city you find is just a mining outpost, hence why there are lots of mines and mining shops, the description should reflect that it is in fact a mining outpost because soon I will impliment different kinds of cities such as slavers dens/arena cities/trade towns/military towns ect

**Comment by Huw2k8** [comment]
Has been fixed in version 0.7.1 which will be out sometime today/tomorrow
